server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bysj?serverTimezone=UTC&useSSL=true
    username: root
    password: hanwei19981030
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置




thymeleaf:
   prefix=classpath:/static/



mybatis:
  mapper-locations:
    - classpath:mapper/*.xml